address.address_format.*:
  type: config_entity
  label: 'Address format'
  mapping:
    countryCode:
      type: string
      label: 'Country code'
    format:
      type: text
      label: 'Format'
    requiredFields:
      type: sequence
      label: 'Required fields'
      sequence:
        - type: string
    uppercaseFields:
      type: sequence
      label: 'Uppercase Fields'
      sequence:
        - type: string
    administrativeAreaType:
      type: string
      label: 'Administrative area type'
    localityType:
      type: string
      label: 'Locality type'
    dependentLocalityType:
      type: string
      label: 'Dependent locality type'
    postalCodeType:
      type: string
      label: 'Postal code type'
    postalCodePattern:
      type: string
      label: 'Postal code pattern'
    postalCodePrefix:
      type: string
      label: 'Postal code prefix'
